pub mod about_window;
pub mod accent;
pub mod detail;
pub mod icon;
pub mod link;
pub mod list_keys;
pub mod menu;
pub mod nav;
pub mod panel;
pub mod picker;
pub mod picker_keys;
pub mod picker_tunnel;
pub mod placeholder;
pub mod raster;
pub mod report_issue;
pub mod settings;
pub mod space;
pub mod status_bar;
pub mod style;
pub mod table_fit;
pub mod text_size;
pub mod theme;
pub mod toolbar;
pub mod tunnels;
pub mod typography;
pub mod unrestored;
pub mod viewer;
pub mod yaml_view;

pub use panel::resource as resource_panel;
pub use panel::title as panel_title;
